sudo: required

language: rust
cache: cargo
dist: trusty
group: edge

os:
  - linux

rust:
  - nightly

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

before_script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - which cargo-coverage || cargo install cargo-travis
  - export RUST_BACKTRACE=1

script:
- |
  cargo clean &&
  cargo build &&
  cargo test

after_success:
- cargo coveralls --verbose

