[package]
name = "jaibon"
version = "0.1.0"
authors = ["Erich Cordoba <erich.cm@yandex.com>"]

[dependencies]
clap = "2.24.1"
clippy = {version = "*", optional = true}
threadpool = "1.3.2"
num_cpus = "1.6.2"

[features]
default = []